version: '3'
services: 
  app:
    build: .
    image: sales_app:latest
    ports: 
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sales_app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: sales_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"